### ISSUE TITLE
 Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by alekspickle** [Dwolla/dwolla-v2-node#29]
Receiving it every time I run the server

<details>
  <summary>full error</summary>
<pre>Unhandled rejection SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/justdoit/Documents/mock-server/node_modules/node-fetch/lib/body.js:48:15
    at tryCatcher (/home/justdoit/Documents/mock-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/justdoit/Documents/mock-server/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/justdoit/Documents/mock-server/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/justdoit/Documents/mock-server/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/justdoit/Documents/mock-server/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/justdoit/Documents/mock-server/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/justdoit/Documents/mock-server/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/justdoit/Documents/mock-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
</pre>
</details>

**Comment by JuneFan** [comment]
Hi,
Did you fixed it?
I also have similar problem.
ERROR in ./~/dwolla-v2/package.json
Module parse failed: D:\ROC_CAPITAL\portal_ui_prv\node_modules\dwolla-v2\package.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack\lib\NormalModule.js:104:16)
    at NormalModule.onModuleBuild (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at D:\ROC_CAPITAL\portal_ui_prv\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.provide (D:\ROC_CAPITAL\portal_ui_prv\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
 @ ./~/dwolla-v2/src/dwolla/userAgent.js 1:14-43

**Comment by alexgnatrow** [comment]
Nope. Turns out this is not critical issue, and both server and app is
working somewhat fine.

After all I use it in firebase functions. The node version there is old, I
think somewhere near 6(they don't even allow async/await).

But it is working so far, and I am not getting this ugly message in
firebase console.



Have a nice day!
Alex Gnatovskyi

**Comment by spencerhunter** [comment]
In response to the error
```
Unhandled rejection SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse ()
```
It looks like the node client is trying to parse something that isn't JSON as JSON and it's failing. My assumption is the API is returning  an HTML response and not JSON. We'll keep this open to update the client to not blow up if something else gets returned other than JSON.
